global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
       - 'alertmanager1:9093'
       - 'alertmanager2:9093'

rule_files:
   - "alert_rules.yml"

scrape_configs:
  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
      - targets: ['node_exporter:9100']
